name: Bug Report
description: Report a bug in the project
title: "Bug: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      placeholder: "A clear and concise description of what the bug is"
      description: "Please provide steps, expected behavior, and any additional info"

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      placeholder: "Describe how to reproduce the bug"

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      placeholder: "What did you expect to happen"
