name: Bug Report # Name der Vorlage
description: Report a bug in the project # Kurze Beschreibung

labels: ["bug"] # Automatisches Label beim Erstellen
title: "Bug: " # Vorgeschlagener Titel für das Issue

body:
  - type: markdown
    content: |
      **Describe the bug**
      A clear and concise description of what the bug is.

  - type: input
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: Describe how to reproduce the bug
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
