name: New Feature
description: ...
title: Feature Name
labels: [enhancement]

body:
  - type: textarea
    attributes:
      label: Describe your Feature
      placeholder: A short and clear description of your feature idea

  - type: checkbox
    attributes:
      label: ...
